"""Initial migration

Revision ID: aa37b075ada1
Revises: 1320828ef91e
Create Date: 2021-08-13 08:24:36.551755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa37b075ada1'
down_revision = '1320828ef91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tittle', sa.Text(), nullable=True))
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.TEXT(), nullable=True))
    op.drop_column('posts', 'tittle')
    # ### end Alembic commands ###
